Repository stripe/stripe-dotnet, pull requests merged in 2018-09, with the labels that each got.

#1253 Properly re-architecture the library to handle various source abstractions
  src/Stripe.net/Entities/BankAccount.cs
  src/Stripe.net/Entities/ExternalAccount.cs
  src/Stripe.net/Entities/PaymentSource.cs
  src/Stripe.net/Entities/StripeAccount.cs
  src/Stripe.net/Entities/StripeBankAccount.cs
  src/Stripe.net/Entities/StripeCharge.cs
  src/Stripe.net/Entities/StripeCustomer.cs
  src/Stripe.net/Entities/StripePayout.cs
  src/Stripe.net/Entities/StripeToken.cs
  src/Stripe.net/Entities/StripeTopup.cs
  src/Stripe.net/Infrastructure/JsonConverters/ExternalAccountConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/PaymentSourceConverter.cs
  src/Stripe.net/Infrastructure/Urls.cs
  src/Stripe.net/Services/BankAccounts/BankAccountService.cs
  src/Stripe.net/Services/Cards/StripeCardCreateOptions.cs
  src/Stripe.net/Services/Cards/StripeCardService.cs
  src/Stripe.net/Services/Charges/StripeChargeCreateOptions.cs
  src/Stripe.net/Services/Customers/StripeCustomerCreateOptions.cs
  src/Stripe.net/Services/Customers/StripeCustomerService.cs
  src/Stripe.net/Services/Customers/StripeCustomerUpdateOptions.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountCardUpdateOptions.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountCreateOptions.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountListOptions.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountService.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountUpdateOptions.cs
  src/Stripe.net/Services/ExternalAccounts/StripeExternalAccountListOptions.cs
  src/Stripe.net/Services/Subscriptions/SubscriptionSharedOptions.cs
  src/Stripe.net/Services/_refactor/CardCreateNestedOptions.cs
  src/Stripe.net/Services/_refactor/SourceBankAccount.cs
  src/StripeTests/Entities/BankAccountTest.cs
  src/StripeTests/Entities/ExternalAccountTest.cs
  src/StripeTests/Entities/StripeBankAccountTest.cs
  src/StripeTests/Entities/StripeCustomerTest.cs
  src/StripeTests/Entities/StripePayoutTest.cs
  src/StripeTests/Entities/StripeTopupTest.cs
  src/StripeTests/Services/Cards/StripeCardServiceTest.cs
  src/StripeTests/Services/ExternalAccounts/ExternalAccountServiceTest.cs
Labels: breaking-api-change

#1273 Add exchange_rate to the Balance Transaction resource
  src/Stripe.net/Entities/StripeBalanceTransaction.cs
Labels: approved

#1270 Add status_transitions filters to the Order List options
  src/Stripe.net/Services/Orders/StripeOrderListOptions.cs
  src/Stripe.net/Services/Orders/StripeOrderStatusTransitionsOptions.cs
Labels: approved

#1280 Enable XML documentation
  src/Stripe.net/Entities/_contracts/ISupportMetadata.cs
  src/Stripe.net/Services/Charges/StripeChargeCaptureOptions.cs
  src/Stripe.net/Services/Charges/StripeChargeCreateOptions.cs
  src/Stripe.net/Services/Subscriptions/SubscriptionSharedOptions.cs
  src/Stripe.net/Services/Topups/StripeTopupCreateOptions.cs
  src/Stripe.net/Stripe.net.csproj
  src/_stylecop/StyleCopRules.ruleset
Labels: approved

#1282 Rename event to match type name and add a related one.
  src/Stripe.net/Constants/StripeEvents.cs
Labels: breaking-api-change

#1285 Rename two properties that start with a lower case letter
  src/Stripe.net/Entities/StripeSku.cs
  src/Stripe.net/Services/Skus/StripeSkuSharedOptions.cs
  src/_stylecop/StyleCopRules.ruleset
Labels: approved, breaking-api-change

#1286 Fix ScheduledQueryRun naming
  src/Stripe.net/Entities/Sigma/ScheduledQueryRun.cs
  src/Stripe.net/Services/Sigma/ScheduledQueryRuns/ScheduledQueryRunListOptions.cs
  src/Stripe.net/Services/Sigma/ScheduledQueryRuns/ScheduledQueryRunService.cs
  src/Stripe.net/Services/Sigma/ScheduledQueryService.cs
  src/StripeTests/Entities/Sigma/ScheduledQueryRunTest.cs
  src/StripeTests/Services/Sigma/ScheduledQueryRuns/ScheduledQueryRunServiceTest.cs
Labels: breaking-api-change

#1288 Fix FileUploadService
  src/Stripe.net/Infrastructure/Requestor.cs
  src/Stripe.net/Services/FileUploads/FileUploadCreateOptions.cs
  src/Stripe.net/Services/FileUploads/FileUploadService.cs
  src/Stripe.net/Stripe.net.csproj
  src/StripeTests/Services/FileUploads/FileUploadServiceTest.cs
Labels: approved, breaking-api-change

#1222 Add support for the PaymentIntent resource
  src/Stripe.net/Entities/PaymentIntents/PaymentIntent.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntentSourceAction.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntentSourceActionAuthorizeWithUrl.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntentTransferData.cs
  src/Stripe.net/Infrastructure/JsonConverters/PaymentIntentSourceActionConverter.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentCancelOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentCaptureOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentConfirmOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentCreateOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentListOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentService.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentSharedOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentTransferDataOptions.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentUpdateOptions.cs
  src/StripeTests/Entities/PaymentIntentTest.cs
  src/StripeTests/Resources/api_fixtures/payment_intent_with_next_source_action.json
  src/StripeTests/Services/PaymentIntents/PaymentIntentServiceTest.cs
Labels: approved

#1302 Upgrade to API version 2018-09-24
  appveyor.yml
  src/Stripe.net/Entities/Account.cs
  src/Stripe.net/Entities/Evidence.cs
  src/Stripe.net/Entities/File.cs
  src/Stripe.net/Entities/FileLink.cs
  src/Stripe.net/Entities/Issuing/EvidenceFraudulent.cs
  src/Stripe.net/Entities/Issuing/EvidenceOther.cs
  src/Stripe.net/Entities/LegalEntityVerification.cs
  src/Stripe.net/Entities/Reporting/ReportRun.cs
  src/Stripe.net/Entities/Sigma/ScheduledQueryRun.cs
  src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs
  src/Stripe.net/Infrastructure/Urls.cs
  src/Stripe.net/Services/FileUploads/FileUploadService.cs
  src/Stripe.net/Services/Files/FileCreateOptions.cs
  src/Stripe.net/Services/Files/FileListOptions.cs
  src/Stripe.net/Services/Files/FileService.cs
  src/Stripe.net/Services/Issuing/Disputes/DisputeCreateOptions.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Entities/AccountTest.cs
  src/StripeTests/Entities/FileTest.cs
  src/StripeTests/Services/FileUploads/FileUploadServiceTest.cs
  src/StripeTests/Services/Files/FileServiceTest.cs
  src/StripeTests/Services/Issuing/Disputes/IssuingDisputeServiceTest.cs
Labels: breaking-api-change

#1297 Cross target netstandard2.0
  src/Stripe.net/Stripe.net.csproj
Labels: approved

#1303 Rename LiveMode to Livemode
  src/Stripe.net/Entities/ApplePayDomain.cs
  src/Stripe.net/Entities/ApplicationFee.cs
  src/Stripe.net/Entities/Balance.cs
  src/Stripe.net/Entities/Charge.cs
  src/Stripe.net/Entities/Coupon.cs
  src/Stripe.net/Entities/Customer.cs
  src/Stripe.net/Entities/Dispute.cs
  src/Stripe.net/Entities/EphemeralKey.cs
  src/Stripe.net/Entities/Event.cs
  src/Stripe.net/Entities/FileLink.cs
  src/Stripe.net/Entities/Invoice.cs
  src/Stripe.net/Entities/InvoiceLineItem.cs
  src/Stripe.net/Entities/Issuing/Authorization.cs
  src/Stripe.net/Entities/Issuing/Card.cs
  src/Stripe.net/Entities/Issuing/Cardholder.cs
  src/Stripe.net/Entities/Issuing/Dispute.cs
  src/Stripe.net/Entities/Issuing/Transaction.cs
  src/Stripe.net/Entities/OAuthToken.cs
  src/Stripe.net/Entities/Order.cs
  src/Stripe.net/Entities/OrderReturn.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntent.cs
  src/Stripe.net/Entities/Payout.cs
  src/Stripe.net/Entities/Plan.cs
  src/Stripe.net/Entities/Product.cs
  src/Stripe.net/Entities/Recipient.cs
  src/Stripe.net/Entities/Reporting/ReportRun.cs
  src/Stripe.net/Entities/Review.cs
  src/Stripe.net/Entities/Sku.cs
  src/Stripe.net/Entities/SourceMandateNotifications/SourceMandateNotification.cs
  src/Stripe.net/Entities/SourceTransactions/SourceTransaction.cs
  src/Stripe.net/Entities/Sources/Source.cs
  src/Stripe.net/Entities/Subscription.cs
  src/Stripe.net/Entities/ThreeDSecure.cs
  src/Stripe.net/Entities/Token.cs
  src/Stripe.net/Entities/Topup.cs
  src/Stripe.net/Entities/Transfer.cs
  src/Stripe.net/Entities/UsageRecord.cs
  src/Stripe.net/Entities/UsageRecordSummary.cs
Labels: approved, breaking-api-change

#1307 Sort service methods alphabetically
  src/Stripe.net/Services/Account/AccountService.cs
  src/Stripe.net/Services/ApplePayDomains/ApplePayDomainService.cs
  src/Stripe.net/Services/ApplicationFeeRefunds/ApplicationFeeRefundService.cs
  src/Stripe.net/Services/ApplicationFees/ApplicationFeeService.cs
  src/Stripe.net/Services/BankAccounts/BankAccountService.cs
  src/Stripe.net/Services/Cards/CardService.cs
  src/Stripe.net/Services/Charges/ChargeService.cs
  src/Stripe.net/Services/CountrySpecs/CountrySpecService.cs
  src/Stripe.net/Services/Coupons/CouponService.cs
  src/Stripe.net/Services/Customers/CustomerService.cs
  src/Stripe.net/Services/Discounts/DiscountService.cs
  src/Stripe.net/Services/Disputes/DisputeService.cs
  src/Stripe.net/Services/EphemeralKeys/EphemeralKeyService.cs
  src/Stripe.net/Services/Events/EventService.cs
  src/Stripe.net/Services/ExchangeRates/ExchangeRateService.cs
  src/Stripe.net/Services/ExternalAccounts/ExternalAccountService.cs
  src/Stripe.net/Services/FileLinks/FileLinkService.cs
  src/Stripe.net/Services/InvoiceItems/InvoiceItemService.cs
  src/Stripe.net/Services/Invoices/InvoiceService.cs
  src/Stripe.net/Services/Issuing/Authorizations/AuthorizationService.cs
  src/Stripe.net/Services/Issuing/Cardholders/CardholderService.cs
  src/Stripe.net/Services/Issuing/Cards/CardService.cs
  src/Stripe.net/Services/Issuing/Disputes/DisputeService.cs
  src/Stripe.net/Services/Issuing/Transactions/TransactionService.cs
  src/Stripe.net/Services/Orders/OrderService.cs
  src/Stripe.net/Services/PaymentIntents/PaymentIntentService.cs
  src/Stripe.net/Services/Payouts/PayoutService.cs
  src/Stripe.net/Services/Plans/PlanService.cs
  src/Stripe.net/Services/Products/ProductService.cs
  src/Stripe.net/Services/Refunds/RefundService.cs
  src/Stripe.net/Services/Reporting/ReportRuns/ReportRunService.cs
  src/Stripe.net/Services/Reporting/ReportTypes/ReportTypeService.cs
  src/Stripe.net/Services/Skus/SkuService.cs
  src/Stripe.net/Services/Sources/SourceService.cs
  src/Stripe.net/Services/SubscriptionItems/SubscriptionItemService.cs
  src/Stripe.net/Services/Subscriptions/SubscriptionService.cs
  src/Stripe.net/Services/Tokens/TokenService.cs
  src/Stripe.net/Services/Topups/TopupService.cs
  src/Stripe.net/Services/TransferReversals/TransferReversalService.cs
  src/Stripe.net/Services/Transfers/TransferService.cs
Labels: approved
