Repository stripe/stripe-dotnet, pull requests merged in 2018-08, with the labels that each got.

#1244 file_link support
  appveyor.yml
  src/Stripe.net/Entities/StripeFileLink.cs
  src/Stripe.net/Entities/StripeFileUpload.cs
  src/Stripe.net/Services/FileLinks/StripeFileLinkCreateOptions.cs
  src/Stripe.net/Services/FileLinks/StripeFileLinkListOptions.cs
  src/Stripe.net/Services/FileLinks/StripeFileLinkService.cs
  src/Stripe.net/Services/FileLinks/StripeFileLinkSharedOptions.cs
  src/Stripe.net/Services/FileLinks/StripeFileLinkUpdateOptions.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Entities/StripeFileLinkTest.cs
  src/StripeTests/Services/FileLinks/StripeFileLinkServiceTest.cs
Labels: approved

#1255 Amount for invoice item is now optional
  src/Stripe.net/Services/InvoiceItems/StripeInvoiceItemCreateOptions.cs
Labels: approved

#1257 Added support for options on the Pay Invoice API
  src/Stripe.net/Services/Invoices/StripeInvoicePayOptions.cs
  src/Stripe.net/Services/Invoices/StripeInvoiceService.cs
  src/StripeTests/Services/Invoices/StripeInvoiceServiceTest.cs
Labels: approved, breaking-api-change

#1259 Upgrade to the latest API version 2018-08-23
  src/Stripe.net/Entities/StripeCustomer.cs
  src/Stripe.net/Entities/StripeCustomerTaxInfo.cs
  src/Stripe.net/Entities/StripeCustomerTaxInfoVerification.cs
  src/Stripe.net/Entities/StripePlanTier.cs
  src/Stripe.net/Entities/StripeProduct.cs
  src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs
  src/Stripe.net/Services/Coupons/StripeCouponCreateOptions.cs
  src/Stripe.net/Services/Customers/StripeCustomerCreateOptions.cs
  src/Stripe.net/Services/Customers/StripeCustomerUpdateOptions.cs
  src/Stripe.net/Services/Plans/StripePlanTierOptions.cs
  src/Stripe.net/Services/StripeCustomerTaxInfoOptions.cs
  src/Stripe.net/Services/Subscriptions/StripeSubscriptionCancelOptions.cs
  src/Stripe.net/Services/Subscriptions/StripeSubscriptionService.Obsolete.cs
  src/Stripe.net/Services/Subscriptions/StripeSubscriptionService.cs
  src/StripeTests/Services/Plans/StripePlanCreateOptionsTest.cs
  src/StripeTests/Services/Subscriptions/StripeSubscriptionServiceTest.cs
Labels: breaking-api-change
