Repository stripe/stripe-dotnet, pull requests merged in 2018-12, with the labels that each got.

#1413 Allow paging on upcoming invoice line items
  src/Stripe.net/Services/Invoices/InvoiceService.cs
  src/Stripe.net/Services/Invoices/UpcomingInvoiceListLineItemsOptions.cs
  src/StripeTests/Entities/Reviews/ReviewTest.cs
  src/StripeTests/Services/Invoices/InvoiceServiceTest.cs
Labels: approved, breaking-api-change

#1418 Replace RecipientActiveAccount with BankAccount
  src/Stripe.net/Entities/Recipients/Recipient.cs
  src/Stripe.net/Entities/Recipients/RecipientActiveAccount.cs
Labels: breaking-api-change

#1396 Fix deserialization logic for polymorphic types
  src/Stripe.net/Entities/Charges/Charge.cs
  src/Stripe.net/Entities/Events/EventData.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntentLastPaymentError.cs
  src/Stripe.net/Entities/PaymentIntents/PaymentIntentSourceAction.cs
  src/Stripe.net/Entities/StripeList.cs
  src/Stripe.net/Infrastructure/JsonConverters/AbstractStripeObjectConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/BalanceTransactionSourceConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/DateTimeConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/ExternalAccountConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/PaymentSourceConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/StripeObjectConverter.cs
  src/Stripe.net/Infrastructure/Public/Mapper.cs
  src/Stripe.net/Infrastructure/StringOrObject.cs
  src/Stripe.net/Infrastructure/StripeTypeRegistry.cs
  src/StripeTests/Entities/Accounts/AccountTest.cs
  src/StripeTests/Entities/Charges/ChargeTest.cs
  src/StripeTests/Entities/Customers/CustomerTest.cs
  src/StripeTests/Entities/Events/EventTest.cs
  src/StripeTests/Entities/PaymentIntents/PaymentIntentTest.cs
  src/StripeTests/Infrastructure/JsonConverters/AbstractStripeObjectConverterTest.cs
  src/StripeTests/Infrastructure/MapperTest.cs
  src/StripeTests/Infrastructure/SerializationTest.cs
  src/StripeTests/Infrastructure/StripeTypeRegistryTest.cs
  src/StripeTests/Resources/api_fixtures/customer_iso_dates.json
  src/StripeTests/Wholesome/AllStripeObjectClassesPresentInDictionary.cs
  src/StripeTests/Wholesome/NullableValueTypes.cs
Labels: approved

#1420 Remove redundant parantheses
  readme.md
  src/Stripe.net/Infrastructure/JsonConverters/BalanceTransactionSourceConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/ExternalAccountConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/PaymentSourceConverter.cs
  src/Stripe.net/Infrastructure/JsonConverters/StripeObjectConverter.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Infrastructure/JsonConverters/AbstractStripeObjectConverterTest.cs
  src/StripeTests/Services/Accounts/AccountServiceTest.cs
  src/StripeTests/Services/ApplePayDomains/ApplePayDomainServiceTest.cs
  src/StripeTests/Services/ApplicationFeeRefunds/ApplicationFeeRefundServiceTest.cs
  src/StripeTests/Services/ApplicationFees/ApplicationFeeServiceTest.cs
  src/StripeTests/Services/BalanceTransactions/BalanceTransactionServiceTest.cs
  src/StripeTests/Services/BankAccounts/BankAccountServiceTest.cs
  src/StripeTests/Services/Cards/CardServiceTest.cs
  src/StripeTests/Services/Charges/ChargeServiceTest.cs
  src/StripeTests/Services/CountrySpecs/CountrySpecServiceTest.cs
  src/StripeTests/Services/Coupons/CouponCreateOptionsTest.cs
  src/StripeTests/Services/Coupons/CouponServiceTest.cs
  src/StripeTests/Services/Customers/CustomerServiceTest.cs
  src/StripeTests/Services/Disputes/DisputeServiceTest.cs
  src/StripeTests/Services/Events/EventServiceTest.cs
  src/StripeTests/Services/ExchangeRates/ExchangeRateServiceTest.cs
  src/StripeTests/Services/ExternalAccounts/ExternalAccountServiceTest.cs
  src/StripeTests/Services/FileLinks/FileLinkServiceTest.cs
  src/StripeTests/Services/Files/FileServiceTest.cs
  src/StripeTests/Services/InvoiceItems/InvoiceItemServiceTest.cs
  src/StripeTests/Services/Invoices/InvoiceServiceTest.cs
  src/StripeTests/Services/Issuing/Authorizations/AuthorizationServiceTest.cs
  src/StripeTests/Services/Issuing/Cardholders/CardholderServiceTest.cs
  src/StripeTests/Services/Issuing/Cards/IssuingCardServiceTest.cs
  src/StripeTests/Services/Issuing/Disputes/IssuingDisputeServiceTest.cs
  src/StripeTests/Services/Issuing/Transactions/TransactionServiceTest.cs
  src/StripeTests/Services/LoginLinks/LoginLinkServiceTest.cs
  src/StripeTests/Services/Orders/OrderServiceTest.cs
  src/StripeTests/Services/Payouts/PayoutServiceTest.cs
  src/StripeTests/Services/Plans/PlanServiceTest.cs
  src/StripeTests/Services/Products/ProductServiceTest.cs
  src/StripeTests/Services/Radar/ValueListItems/ValueListItemServiceTest.cs
  src/StripeTests/Services/Radar/ValueLists/ValueListServiceTest.cs
  src/StripeTests/Services/Refunds/RefundServiceTest.cs
  src/StripeTests/Services/Sigma/ScheduledQueryRuns/ScheduledQueryRunServiceTest.cs
  src/StripeTests/Services/Skus/SkuServiceTest.cs
  src/StripeTests/Services/SourceTransactions/SourceTransactionServiceTest.cs
  src/StripeTests/Services/Sources/SourceServiceTest.cs
  src/StripeTests/Services/SubscriptionItems/SubscriptionItemServiceTest.cs
  src/StripeTests/Services/Subscriptions/SubscriptionCreateOptionsTest.cs
  src/StripeTests/Services/Subscriptions/SubscriptionServiceTest.cs
  src/StripeTests/Services/ThreeDSecure/ThreeDSecureServiceTest.cs
  src/StripeTests/Services/Topups/TopupServiceTest.cs
  src/StripeTests/Services/TransferReversals/TransferReversalServiceTest.cs
  src/StripeTests/Services/Transfers/TransferServiceTest.cs
  src/StripeTests/Services/UsageRecordSummaries/UsageRecordSummaryServiceTest.cs
  src/StripeTests/Services/UsageRecords/UsageRecordServiceTest.cs
  src/StripeTests/Services/WebhookEndpoints/WebhookEndpointServiceTest.cs
Labels: approved

#1419 Replace public fields with properties
  src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs
  src/Stripe.net/Services/BaseOptions.cs
Labels: approved

#1421 More code cleanup
  src/Stripe.net/Services/Subscriptions/SubscriptionService.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Infrastructure/ClientTest.cs
  src/StripeTests/Infrastructure/ParameterBuilderTest.cs
  src/StripeTests/Infrastructure/RequestorTest.cs
  src/StripeTests/Infrastructure/SerializationTest.cs
  src/StripeTests/Infrastructure/StringOrObjectTest.cs
  src/StripeTests/Infrastructure/StripeExceptionTest.cs
  src/StripeTests/Infrastructure/TestData/TestOptions.cs
  src/StripeTests/Services/Products/ProductServiceTest.cs
  src/StripeTests/Services/WebhookEndpoints/WebhookEndpointServiceTest.cs
Labels: approved

#1423 Replace constants with static read-only properties
  src/Stripe.net/Constants/AccountType.cs
  src/Stripe.net/Constants/BankAccountHolderType.cs
  src/Stripe.net/Constants/Events.cs
  src/Stripe.net/Constants/FilePurpose.cs
  src/Stripe.net/Constants/PlanIntervals.cs
  src/Stripe.net/Constants/RefundReasons.cs
  src/Stripe.net/Constants/SourceFlow.cs
  src/Stripe.net/Constants/SourceType.cs
  src/Stripe.net/Constants/SourceUsage.cs
  src/Stripe.net/Constants/SubscriptionStatuses.cs
  src/Stripe.net/Constants/TransferFailureCodes.cs
  src/Stripe.net/Constants/TransferMethod.cs
Labels: approved

#1428 Make ObjectsToTypes dictionary immutable
  src/Stripe.net/Infrastructure/StripeTypeRegistry.cs
  src/Stripe.net/Stripe.net.csproj
Labels: approved

#1429 Remove StripeList.TotalCount
  src/Stripe.net/Entities/StripeList.cs
  src/Stripe.net/Services/ListOptions.cs
  src/Stripe.net/Services/ListOptionsWithCreated.cs
Labels: approved, breaking-api-change

#1432 Upgrade stripe-mock to 0.39.0
  appveyor.yml
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Services/Terminal/Locations/LocationServiceTest.cs
Labels: approved

#1434 Make Deleted nullable on all Stripe objects
  src/Stripe.net/Entities/Accounts/Account.cs
  src/Stripe.net/Entities/ApplePayDomains/ApplePayDomain.cs
  src/Stripe.net/Entities/BankAccounts/BankAccount.cs
  src/Stripe.net/Entities/Cards/Card.cs
  src/Stripe.net/Entities/Coupons/Coupon.cs
  src/Stripe.net/Entities/Discounts/Discount.cs
  src/Stripe.net/Entities/EphemeralKeys/EphemeralKey.cs
  src/Stripe.net/Entities/InvoiceItems/InvoiceItem.cs
  src/Stripe.net/Entities/Persons/Person.cs
  src/Stripe.net/Entities/Plans/Plan.cs
  src/Stripe.net/Entities/Products/Product.cs
  src/Stripe.net/Entities/Skus/Sku.cs
  src/Stripe.net/Entities/SubscriptionItems/SubscriptionItem.cs
  src/Stripe.net/Entities/WebhookEndpoints/WebhookEndpoint.cs
Labels: approved, breaking-api-change

#1438 Fix license packaging
  LICENSE.txt
  src/Stripe.net/Stripe.net.csproj
Labels: approved

#1439 Fix some remaining StyleCop rules violations
  src/Stripe.net/Enums/Billing.cs
  src/Stripe.net/Infrastructure/Middleware/RequestStringBuilder.cs
  src/Stripe.net/Stripe.net.csproj
  src/StripeTests/StripeTests.csproj
  src/_stylecop/StyleCopRules.ruleset
Labels: approved

#1441 Disable optimizations in SecureCompare
  src/Stripe.net/Services/Events/EventUtility.cs
Labels: approved

#1449 Add support for invoice_now and prorate on subscription cancelation
  src/Stripe.net/Services/Subscriptions/SubscriptionCancelOptions.cs
  src/StripeTests/Services/Subscriptions/SubscriptionServiceTest.cs
Labels: approved
