Repository stripe/stripe-dotnet, pull requests merged in 2018-07, with the labels that each got.

#1223 Add missing property/params to the InvoiceItem resource
  src/Stripe.net/Entities/StripeInvoiceLineItem.cs
  src/Stripe.net/Services/InvoiceItems/StripeInvoiceItemCreateOptions.cs
  src/Stripe.net/Services/InvoiceItems/StripeInvoiceItemUpdateOptions.cs
Labels: breaking-api-change

#1224 Improve tolerance verification to check both past and future timestamps
  src/Stripe.net/Services/Events/StripeEventUtility.cs
Labels: approved

#1214 Upcoming now has `invoice_items` and subscription_billing_cycle_anchor`
  src/Stripe.Tests.XUnit/invoices/retrieving_upcoming_invoice.cs
  src/Stripe.net/Services/Invoices/StripeInvoiceUpcomingInvoiceItemOption.cs
  src/Stripe.net/Services/Invoices/StripeUpcomingInvoiceOptions.cs
Labels: approved

#1210 Add the 'customer.source.expiring' event and fix a typo
  src/Stripe.net/Constants/StripeEvents.cs
Labels: approved, breaking-api-change

#1229 BaseStripeTest class with stripe-mock setup
  appveyor.yml
  src/Stripe.Tests.XUnit/Stripe.Tests.XUnit.csproj
  src/Stripe.net.sln
  src/Stripe.net/Properties/InternalsVisibleTo.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Entities/StripeCouponTest.cs
  src/StripeTests/Services/Coupons/StripeCouponCreateOptionsTest.cs
  src/StripeTests/Services/Coupons/StripeCouponServiceTest.cs
  src/StripeTests/StripeTests.csproj
Labels: approved

#1165 Properly deserialize source on BT during expand
  src/Stripe.net/Entities/BalanceTransactionSource.cs
  src/Stripe.net/Entities/StripeBalanceTransaction.cs
  src/Stripe.net/Infrastructure/JsonConverters/BalanceTransactionSourceConverter.cs
  src/StripeTests/BaseStripeTest.cs
  src/StripeTests/Entities/StripeBalanceTransactionTest.cs
  src/StripeTests/Resources/api_fixtures/balance_transaction_with_expansion.json
  src/StripeTests/StripeTests.csproj
Labels: approved

#1242 Add account.created field
  src/Stripe.net/Entities/StripeAccount.cs
Labels: approved
