Repository stripe/stripe-dotnet, pull requests merged in 2018-03, with the labels that each got.

#1123 Bump Newtonsoft.Json version to 11.0.1
  src/Stripe.net/Stripe.net.csproj
Labels: approved

#1119 Adds the `FailureReason` property to `StripeRedirect`
  src/Stripe.net/Entities/Sources/StripeRedirect.cs
  src/Stripe.net/Enums/StripeRedirectFailureReason.cs
Labels: approved

#1135 Add ProductId parameter to StripePlanListOptions
  src/Stripe.net/Services/Plans/StripePlanListOptions.cs
Labels: approved

#1138 Add support for redirect_url when creating login_links
  src/Stripe.Tests.XUnit/login_links/when_creating_login_links.cs
  src/Stripe.net/Services/LoginLink/StripeLoginLinkCreateOptions.cs
  src/Stripe.net/Services/LoginLink/StripeLoginLinkService.cs
Labels: breaking-api-change

#1139 Add support for more Expand and change Outcome to be auto expanded
  src/Stripe.Tests.XUnit/charges/creating_updating_and_capturing_charges.cs
  src/Stripe.Tests.XUnit/skus/when_listing_skus.cs
  src/Stripe.net/Entities/StripeAccount.cs
  src/Stripe.net/Entities/StripeApplicationFeeRefund.cs
  src/Stripe.net/Entities/StripeCharge.cs
  src/Stripe.net/Entities/StripeInvoice.cs
  src/Stripe.net/Entities/StripeInvoiceLineItem.cs
  src/Stripe.net/Entities/StripeOutcome.cs
  src/Stripe.net/Entities/StripeSku.cs
  src/Stripe.net/Entities/StripeTransfer.cs
  src/Stripe.net/Services/Account/StripeAccountService.cs
  src/Stripe.net/Services/ApplicationFeeRefunds/StripeApplicationFeeRefundService.cs
  src/Stripe.net/Services/ApplicationFees/StripeApplicationFeeService.cs
  src/Stripe.net/Services/Charges/StripeChargeService.cs
  src/Stripe.net/Services/InvoiceItems/StripeInvoiceItemService.cs
  src/Stripe.net/Services/Invoices/StripeInvoiceService.cs
  src/Stripe.net/Services/Orders/StripeOrderService.cs
  src/Stripe.net/Services/Payouts/StripePayoutService.cs
  src/Stripe.net/Services/Refunds/StripeRefundService.cs
  src/Stripe.net/Services/Skus/StripeSkuService.cs
  src/Stripe.net/Services/Transfers/StripeTransferService.cs
Labels: approved, breaking-api-change

#1143 Use parser plugins during SubscriptionItemUpdatedPlugin item creation
  src/Stripe.Tests.XUnit/subscriptions/_fixture.cs
  src/Stripe.Tests.XUnit/subscriptions/creating_and_updating_subscriptions.cs
  src/Stripe.net/Infrastructure/Middleware/ParserPlugin/SubscriptionItemUpdatedPlugin.cs
Labels: approved
